# Generated by Django 4.2.3 on 2023-07-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cocktail_mocktail_shooter_delete_drink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mocktail',
            options={},
        ),
    ]
